/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SigninRouteRouteImport } from './routes/signin/route'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardMockDemoRouteImport } from './routes/dashboard/mock-demo'
import { Route as DashboardWalletRouteRouteImport } from './routes/dashboard/wallet/route'
import { Route as DashboardSubmissionsRouteRouteImport } from './routes/dashboard/submissions/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardOverviewRouteRouteImport } from './routes/dashboard/overview/route'
import { Route as DashboardMessagesRouteRouteImport } from './routes/dashboard/messages/route'
import { Route as DashboardCreatorsRouteRouteImport } from './routes/dashboard/creators/route'
import { Route as DashboardContestBoardRouteRouteImport } from './routes/dashboard/contest-board/route'
import { Route as DashboardCampaignsRouteRouteImport } from './routes/dashboard/campaigns/route'
import { Route as DashboardSubmissionsIdRouteRouteImport } from './routes/dashboard/submissions/$id/route'
import { Route as DashboardCampaignsIdSelectWinnersRouteRouteImport } from './routes/dashboard/campaigns/$id/select-winners/route'
import { Route as DashboardCampaignsIdBoardRouteRouteImport } from './routes/dashboard/campaigns/$id/board/route'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRouteRoute = SigninRouteRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMockDemoRoute = DashboardMockDemoRouteImport.update({
  id: '/mock-demo',
  path: '/mock-demo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRouteRoute = DashboardWalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRouteRoute =
  DashboardSubmissionsRouteRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRouteRoute = DashboardOverviewRouteRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRouteRoute = DashboardMessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreatorsRouteRoute = DashboardCreatorsRouteRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContestBoardRouteRoute =
  DashboardContestBoardRouteRouteImport.update({
    id: '/contest-board',
    path: '/contest-board',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCampaignsRouteRoute = DashboardCampaignsRouteRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsIdRouteRoute =
  DashboardSubmissionsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardSubmissionsRouteRoute,
  } as any)
const DashboardCampaignsIdSelectWinnersRouteRoute =
  DashboardCampaignsIdSelectWinnersRouteRouteImport.update({
    id: '/$id/select-winners',
    path: '/$id/select-winners',
    getParentRoute: () => DashboardCampaignsRouteRoute,
  } as any)
const DashboardCampaignsIdBoardRouteRoute =
  DashboardCampaignsIdBoardRouteRouteImport.update({
    id: '/$id/board',
    path: '/$id/board',
    getParentRoute: () => DashboardCampaignsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRouteRoute
  '/signin': typeof SigninRouteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/campaigns': typeof DashboardCampaignsRouteRouteWithChildren
  '/dashboard/contest-board': typeof DashboardContestBoardRouteRoute
  '/dashboard/creators': typeof DashboardCreatorsRouteRoute
  '/dashboard/messages': typeof DashboardMessagesRouteRoute
  '/dashboard/overview': typeof DashboardOverviewRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRouteRouteWithChildren
  '/dashboard/wallet': typeof DashboardWalletRouteRoute
  '/dashboard/mock-demo': typeof DashboardMockDemoRoute
  '/dashboard/submissions/$id': typeof DashboardSubmissionsIdRouteRoute
  '/dashboard/campaigns/$id/board': typeof DashboardCampaignsIdBoardRouteRoute
  '/dashboard/campaigns/$id/select-winners': typeof DashboardCampaignsIdSelectWinnersRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRouteRoute
  '/signin': typeof SigninRouteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/campaigns': typeof DashboardCampaignsRouteRouteWithChildren
  '/dashboard/contest-board': typeof DashboardContestBoardRouteRoute
  '/dashboard/creators': typeof DashboardCreatorsRouteRoute
  '/dashboard/messages': typeof DashboardMessagesRouteRoute
  '/dashboard/overview': typeof DashboardOverviewRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRouteRouteWithChildren
  '/dashboard/wallet': typeof DashboardWalletRouteRoute
  '/dashboard/mock-demo': typeof DashboardMockDemoRoute
  '/dashboard/submissions/$id': typeof DashboardSubmissionsIdRouteRoute
  '/dashboard/campaigns/$id/board': typeof DashboardCampaignsIdBoardRouteRoute
  '/dashboard/campaigns/$id/select-winners': typeof DashboardCampaignsIdSelectWinnersRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRouteRoute
  '/signin': typeof SigninRouteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/campaigns': typeof DashboardCampaignsRouteRouteWithChildren
  '/dashboard/contest-board': typeof DashboardContestBoardRouteRoute
  '/dashboard/creators': typeof DashboardCreatorsRouteRoute
  '/dashboard/messages': typeof DashboardMessagesRouteRoute
  '/dashboard/overview': typeof DashboardOverviewRouteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRouteRouteWithChildren
  '/dashboard/wallet': typeof DashboardWalletRouteRoute
  '/dashboard/mock-demo': typeof DashboardMockDemoRoute
  '/dashboard/submissions/$id': typeof DashboardSubmissionsIdRouteRoute
  '/dashboard/campaigns/$id/board': typeof DashboardCampaignsIdBoardRouteRoute
  '/dashboard/campaigns/$id/select-winners': typeof DashboardCampaignsIdSelectWinnersRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/signin'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/dashboard/contest-board'
    | '/dashboard/creators'
    | '/dashboard/messages'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/wallet'
    | '/dashboard/mock-demo'
    | '/dashboard/submissions/$id'
    | '/dashboard/campaigns/$id/board'
    | '/dashboard/campaigns/$id/select-winners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/signin'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/dashboard/contest-board'
    | '/dashboard/creators'
    | '/dashboard/messages'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/wallet'
    | '/dashboard/mock-demo'
    | '/dashboard/submissions/$id'
    | '/dashboard/campaigns/$id/board'
    | '/dashboard/campaigns/$id/select-winners'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/signin'
    | '/dashboard'
    | '/dashboard/campaigns'
    | '/dashboard/contest-board'
    | '/dashboard/creators'
    | '/dashboard/messages'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/submissions'
    | '/dashboard/wallet'
    | '/dashboard/mock-demo'
    | '/dashboard/submissions/$id'
    | '/dashboard/campaigns/$id/board'
    | '/dashboard/campaigns/$id/select-winners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRouteRoute: typeof RegisterRouteRoute
  SigninRouteRoute: typeof SigninRouteRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mock-demo': {
      id: '/dashboard/mock-demo'
      path: '/mock-demo'
      fullPath: '/dashboard/mock-demo'
      preLoaderRoute: typeof DashboardMockDemoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/creators': {
      id: '/dashboard/creators'
      path: '/creators'
      fullPath: '/dashboard/creators'
      preLoaderRoute: typeof DashboardCreatorsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contest-board': {
      id: '/dashboard/contest-board'
      path: '/contest-board'
      fullPath: '/dashboard/contest-board'
      preLoaderRoute: typeof DashboardContestBoardRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions/$id': {
      id: '/dashboard/submissions/$id'
      path: '/$id'
      fullPath: '/dashboard/submissions/$id'
      preLoaderRoute: typeof DashboardSubmissionsIdRouteRouteImport
      parentRoute: typeof DashboardSubmissionsRouteRoute
    }
    '/dashboard/campaigns/$id/select-winners': {
      id: '/dashboard/campaigns/$id/select-winners'
      path: '/$id/select-winners'
      fullPath: '/dashboard/campaigns/$id/select-winners'
      preLoaderRoute: typeof DashboardCampaignsIdSelectWinnersRouteRouteImport
      parentRoute: typeof DashboardCampaignsRouteRoute
    }
    '/dashboard/campaigns/$id/board': {
      id: '/dashboard/campaigns/$id/board'
      path: '/$id/board'
      fullPath: '/dashboard/campaigns/$id/board'
      preLoaderRoute: typeof DashboardCampaignsIdBoardRouteRouteImport
      parentRoute: typeof DashboardCampaignsRouteRoute
    }
  }
}

interface DashboardCampaignsRouteRouteChildren {
  DashboardCampaignsIdBoardRouteRoute: typeof DashboardCampaignsIdBoardRouteRoute
  DashboardCampaignsIdSelectWinnersRouteRoute: typeof DashboardCampaignsIdSelectWinnersRouteRoute
}

const DashboardCampaignsRouteRouteChildren: DashboardCampaignsRouteRouteChildren =
  {
    DashboardCampaignsIdBoardRouteRoute: DashboardCampaignsIdBoardRouteRoute,
    DashboardCampaignsIdSelectWinnersRouteRoute:
      DashboardCampaignsIdSelectWinnersRouteRoute,
  }

const DashboardCampaignsRouteRouteWithChildren =
  DashboardCampaignsRouteRoute._addFileChildren(
    DashboardCampaignsRouteRouteChildren,
  )

interface DashboardSubmissionsRouteRouteChildren {
  DashboardSubmissionsIdRouteRoute: typeof DashboardSubmissionsIdRouteRoute
}

const DashboardSubmissionsRouteRouteChildren: DashboardSubmissionsRouteRouteChildren =
  {
    DashboardSubmissionsIdRouteRoute: DashboardSubmissionsIdRouteRoute,
  }

const DashboardSubmissionsRouteRouteWithChildren =
  DashboardSubmissionsRouteRoute._addFileChildren(
    DashboardSubmissionsRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardCampaignsRouteRoute: typeof DashboardCampaignsRouteRouteWithChildren
  DashboardContestBoardRouteRoute: typeof DashboardContestBoardRouteRoute
  DashboardCreatorsRouteRoute: typeof DashboardCreatorsRouteRoute
  DashboardMessagesRouteRoute: typeof DashboardMessagesRouteRoute
  DashboardOverviewRouteRoute: typeof DashboardOverviewRouteRoute
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRoute
  DashboardSubmissionsRouteRoute: typeof DashboardSubmissionsRouteRouteWithChildren
  DashboardWalletRouteRoute: typeof DashboardWalletRouteRoute
  DashboardMockDemoRoute: typeof DashboardMockDemoRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignsRouteRoute: DashboardCampaignsRouteRouteWithChildren,
  DashboardContestBoardRouteRoute: DashboardContestBoardRouteRoute,
  DashboardCreatorsRouteRoute: DashboardCreatorsRouteRoute,
  DashboardMessagesRouteRoute: DashboardMessagesRouteRoute,
  DashboardOverviewRouteRoute: DashboardOverviewRouteRoute,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRoute,
  DashboardSubmissionsRouteRoute: DashboardSubmissionsRouteRouteWithChildren,
  DashboardWalletRouteRoute: DashboardWalletRouteRoute,
  DashboardMockDemoRoute: DashboardMockDemoRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRouteRoute: RegisterRouteRoute,
  SigninRouteRoute: SigninRouteRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
